name: build-and-deploy-backend

on:
  push:
    branches:
      - main
    paths:
        - "zms-backend/**"
  
  pull_request:
      branches:
        - main
      paths:
        - "zms-backend/**"
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./zms-backend/Dockerfile.Backend
            push: true
            tags: shishuranjan/zms:latest
        - name: verify pushed image
          run: |
            docker pull shishuranjan/zms:latest 
            docker run -d -p 3000:3000 shishuranjan/zms:latest
        
        - name : Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_HOSTNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
               docker stop zms || true
               docker rmi shishuranjan/zms:latest || true
               docker rm zms || true
               docker pull shishuranjan/zms:latest
               docker run -d \
                -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
                --name zms \
                -p 3000:3000 \
                shishuranjan/zms:latest